#pragma once

#include "NativeGameplayTags.h"

namespace GameplayTags
{
	namespace State
	{
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LockOn);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dodge);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Invincible);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IsGoingToDie);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IsParrying);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IsGuardBroken);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IsHeavyAttack);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyAttackCharageEnd);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IsGroggy);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KnockDown);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CanFatal);

		namespace Combat
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ComboWindow);
		}
		
		namespace Stamina
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RegenBlocked);
		}

		namespace Setup
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Completed);
		}
	}
	
	namespace Input
	{
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dodge);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Block);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyAttack);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FatalAttack);
	}
	
	namespace Event
	{
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dodge_End);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Death);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boss_Death);
		namespace Combo
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WindowOpen);
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputPressed);
		}
		namespace Character
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdoll);
		}
		namespace Boss
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DeathCompleted);
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KnockDown);
		}
	}

	namespace Data
	{
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroggyDamage);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackDamage);
		namespace Cost
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stamina);
		}
	}
	
	namespace HitReact
	{
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Front);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Back);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Right);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Left);
	}

	namespace Ability
	{
		namespace Action
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dodge);
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attack);
		}
		
		namespace Boss
		{
			ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BasicAttack);
		}
	}
	
	namespace GameplayEvent
	{
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact);
	}
	
	namespace Attack
	{
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackCombo1);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackCombo2);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackCombo3);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttackCombo4);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyAttack);
		ASHENDUEL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroggyAttack);
	}
}
